### ISSUE TITLE
Warning in profile page UI

### ISSUE THREAD

**Issue by rohitsuratekar** [dilawar/Hippo#28]
I m getting following warning on profile page. Another thing, "all bookings" page keep refreshing. 
<img width="838" alt="bug" src="https://user-images.githubusercontent.com/8757115/33977849-dc46e4e8-e0c2-11e7-9c70-85f555dedfc6.png">

**Comment by dilawar** [comment]
Specialization error is fixed by recent most commit. 

The refresh is intentional. This page is used by security; auto-refresh (every 180seconds) to keep the page updated.

**Comment by rohitsuratekar** [comment]
Instead use some broadcaster to update fields ? Don't know if PHP has one. 
Also why "target : _blank" for every hyperlink? It is annoying.

**Comment by dilawar** [comment]
I have not (yet) put AJAX support in Hippo. JS/AJAX can do this
transparently.  Autorefresh was the quickest solution I found for keep the
page updated.

Each link as a separate page is definitely annoying. These are the pages
which does not require log/in from internet and suppose to have quick
information.  From outside one needs to login to see content on 'most' of
these pages.

Not sure what could be a better design?

Having a navigation bar in side and let all pages opens in one window is
one potential solution.

Till a better solution is found, I'll let only one extra window opens up by
Hippo; any extra popup shall write on the second window only.

**Comment by rohitsuratekar** [comment]
Let's see. I will try out some UI designs and will send you some ideas. Is there any restriction on what framework to use for front end? PHP is very ugly for UI/UX.

**Comment by dilawar** [comment]
Nah. As long as I can integrate PHP calls into framework, it's fine.

PHP has a wonderful database and date time library. Those two things were essential for bookmyvenue. Moreover I got PHP google Calendar API to work quite easily. So stuck with PHP. 

⁣Sent from Blue ​
