### ISSUE TITLE
Fatal error in statistics page

### ISSUE THREAD

**Issue by rohitsuratekar** [dilawar/Hippo#34]
I am getting following exception in "https://ncbs.res.in/hippo/statistics.php" page,

Fatal error: Uncaught TypeError: Argument 1 passed to __get__() must be of the type array, boolean given, called in /var/www/html/hippo/database/helper.php on line 2779 and defined in /var/www/html/hippo/methods.php:251 Stack trace: #0 /var/www/html/hippo/database/helper.php(2779): __get__(false, 'pi_or_host', '') #1 /var/www/html/hippo/statistics.php(324): getPIOrHost('ashwinig') #2 {main} thrown in /var/www/html/hippo/methods.php on line 251

<img width="830" alt="untitled" src="https://user-images.githubusercontent.com/8757115/38419200-1f1a47e4-39bd-11e8-83d0-987059902023.png">

**Comment by dilawar** [comment]
Oh no. Thanks. Will fix it.

Added static type checking in many function. Next week gonna be nightmare.

**Comment by dilawar** [comment]
31ad06ecff880249f3044 fixes it. 

There may be some similar issues hiding somewhere. If you notice, please let me know. Closing this one.,
