### ISSUE TITLE
Can't delete subscribers to a journal club after sorting the list of subscribers with '#PRESENTATIONS'

### ISSUE THREAD

**Issue by analkumar2** [dilawar/hippo#4]
Steps to reproduce:

1. If you are an admin of a journal club, go to https://ncbs.res.in/hippo/user/jcadmin
2. Click on '#PRESENTATIONS' to sort the subscribers.
3. Click on the red delete button.
4. A box will pop up saying: ALERT! Destructive operation! Continue?
5. Clicking ok does nothing.

**Comment by dilawar** [comment]
This wont be fixed in this repo. Use the new app.
